version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "ueda-todo-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-t3smooly3wwi"
s3_prefix = "ueda-todo-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = ["TodoAppFunction=280107060642.dkr.ecr.ap-northeast-1.amazonaws.com/uedatodoapp594f9282/todoappfunctiond1342d42repo"]
disable_rollback = false
