AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: WAF Template

Resources:
  WebACLForApiGateway:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: "WebACLForApiGateway"
      Scope: REGIONAL
      DefaultAction:
        Block: {}
      Rules:
      - Name: "AllowIPRule"
        Action:
          Allow: {}
        Priority: 1
        Statement:
          IPSetReferenceStatement:
            Arn : !GetAtt AllowIPSet.Arn
        VisibilityConfig:
          CloudWatchMetricsEnabled: true
          SampledRequestsEnabled: false
          MetricName: WebACLRuleIPSetMetric
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: false
        MetricName: WebACLMetric

  AllowIPSet:
    Type: "AWS::WAFv2::IPSet"
    Properties:
      Name: "VPNIPSet"
      Scope: "REGIONAL"
      IPAddressVersion: IPV4
      Addresses:
        - 52.192.209.10/32

Outputs:
  WAFWebACLArn:
    Value: !GetAtt WebACLForApiGateway.Arn
    Export:
      Name: WebACLForApiGatewayArn
