AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'todo-app

  Sample SAM Template for todo-app

  '
Globals:
  Function:
    Timeout: 5
Resources:
  TodoAppFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
      - x86_64
      Policies: AmazonDynamoDBFullAccess
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          DYNAMODB_ENDPOINT: ""
      ImageUri: todoappfunction:go1.x-v1
    Metadata:
      DockerContext: ./todo-app
      DockerTag: go1.x-v1
      Dockerfile: Dockerfile.production
      SamResourceId: TodoAppFunction

  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Todo
      AttributeDefinitions:
      - AttributeName: ID
        AttributeType: N
      KeySchema:
      - AttributeName: ID
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST

  SequenceTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Sequences
      AttributeDefinitions:
      - AttributeName: Name
        AttributeType: S
      KeySchema:
      - AttributeName: Name
        KeyType: HASH
      BillingMode: PAY_PER_REQUEST